/** Standard MCC (Merchant Category Code) business-type catalog, per ISO 18245.
 * Curated to the codes commonly used in acquiring/payments — not the full
 * ISO list (700+ codes, many rarely used in practice). */
export interface MccCode {
  code: string;
  description: string;
}

export const MCC_CODES: MccCode[] = [
  { code: '0742', description: 'Veterinary Services' },
  { code: '0763', description: 'Agricultural Cooperatives' },
  { code: '0780', description: 'Landscaping & Horticultural Services' },
  { code: '1520', description: 'General Contractors – Residential & Commercial' },
  { code: '1731', description: 'Electrical Contractors' },
  { code: '1740', description: 'Masonry, Stonework & Plastering' },
  { code: '1750', description: 'Carpentry Contractors' },
  { code: '1761', description: 'Roofing & Siding' },
  { code: '1771', description: 'Concrete Work Contractors' },
  { code: '1799', description: 'Special Trade Contractors' },
  { code: '2741', description: 'Publishing & Printing Services' },
  { code: '2842', description: 'Specialty Cleaning Products' },
  { code: '3000', description: 'Airlines' },
  { code: '4111', description: 'Local & Suburban Commuter Transport' },
  { code: '4121', description: 'Taxicabs & Limousines' },
  { code: '4131', description: 'Bus Lines' },
  { code: '4214', description: 'Motor Freight Carriers & Trucking' },
  { code: '4225', description: 'Public Warehousing & Storage' },
  { code: '4411', description: 'Cruise Lines' },
  { code: '4468', description: 'Marinas & Marine Service' },
  { code: '4511', description: 'Airlines & Air Carriers' },
  { code: '4722', description: 'Travel Agencies & Tour Operators' },
  { code: '4784', description: 'Toll & Bridge Fees' },
  { code: '4812', description: 'Telecommunication Equipment' },
  { code: '4814', description: 'Telecommunication Services (Airtime, Data)' },
  { code: '4816', description: 'Computer Network / Information Services' },
  { code: '4821', description: 'Telegraph Services' },
  { code: '4829', description: 'Money Transfer / Wire Transfer Services' },
  { code: '4899', description: 'Cable, Satellite & Pay TV Services' },
  { code: '4900', description: 'Utilities – Electric, Gas, Water, Sanitary' },
  { code: '5013', description: 'Motor Vehicle Supplies & New Parts' },
  { code: '5021', description: 'Office & Commercial Furniture' },
  { code: '5039', description: 'Construction Materials' },
  { code: '5044', description: 'Office, Photographic & Photocopy Equipment' },
  { code: '5045', description: 'Computers & Computer Peripheral Equipment' },
  { code: '5046', description: 'Commercial Equipment' },
  { code: '5051', description: 'Metal Service Centers' },
  { code: '5065', description: 'Electrical Parts & Equipment' },
  { code: '5072', description: 'Hardware, Equipment & Supplies' },
  { code: '5085', description: 'Industrial Supplies' },
  { code: '5111', description: 'Stationery, Office Supplies' },
  { code: '5122', description: 'Drugs, Drug Proprietaries & Pharmaceuticals' },
  { code: '5131', description: 'Piece Goods, Notions & Dry Goods' },
  { code: '5137', description: 'Uniforms & Commercial Clothing' },
  { code: '5139', description: 'Commercial Footwear' },
  { code: '5169', description: 'Chemicals & Allied Products' },
  { code: '5172', description: 'Petroleum & Petroleum Products' },
  { code: '5192', description: 'Books, Periodicals & Newspapers' },
  { code: '5193', description: 'Florists Supplies, Nursery Stock' },
  { code: '5198', description: 'Paint, Varnishes & Supplies' },
  { code: '5199', description: 'Non-Durable Goods' },
  { code: '5200', description: 'Home Supply Warehouse Stores' },
  { code: '5211', description: 'Lumber & Building Materials' },
  { code: '5231', description: 'Glass, Paint & Wallpaper Stores' },
  { code: '5251', description: 'Hardware Stores' },
  { code: '5261', description: 'Nurseries & Garden / Lawn Supply Stores' },
  { code: '5271', description: 'Mobile Home Dealers' },
  { code: '5300', description: 'Wholesale Clubs' },
  { code: '5309', description: 'Duty Free Stores' },
  { code: '5310', description: 'Discount Stores' },
  { code: '5311', description: 'Department Stores' },
  { code: '5331', description: 'Variety Stores' },
  { code: '5399', description: 'General Merchandise Stores' },
  { code: '5411', description: 'Grocery Stores / Supermarkets' },
  { code: '5422', description: 'Meat, Poultry & Seafood Shops' },
  { code: '5441', description: 'Candy, Nut & Confectionery Shops' },
  { code: '5451', description: 'Dairy Products Stores' },
  { code: '5462', description: 'Bakeries' },
  { code: '5499', description: 'Convenience Stores & Specialty Food Shops' },
  { code: '5511', description: 'Car & Truck Dealers – New & Used' },
  { code: '5521', description: 'Car & Truck Dealers – Used Only' },
  { code: '5531', description: 'Auto & Home Supply Stores' },
  { code: '5532', description: 'Automotive Tire Stores' },
  { code: '5533', description: 'Automotive Parts & Accessories Stores' },
  { code: '5541', description: 'Service Stations (Fuel)' },
  { code: '5542', description: 'Automated Fuel Dispensers' },
  { code: '5551', description: 'Boat Dealers' },
  { code: '5561', description: 'Motorcycle Shops & Dealers' },
  { code: '5571', description: 'Motorcycle & Moped Dealers' },
  { code: '5592', description: 'Motor Homes Dealers' },
  { code: '5599', description: 'Miscellaneous Automotive Dealers' },
  { code: '5611', description: "Men's & Boys' Clothing & Accessories Stores" },
  { code: '5621', description: "Women's Ready-to-Wear Stores" },
  { code: '5631', description: "Women's Accessory & Specialty Shops" },
  { code: '5641', description: "Children's & Infants' Wear Stores" },
  { code: '5651', description: 'Family Clothing Stores' },
  { code: '5655', description: 'Sports & Riding Apparel Stores' },
  { code: '5661', description: 'Shoe Stores' },
  { code: '5681', description: 'Furriers & Fur Shops' },
  { code: '5691', description: "Men's & Women's Clothing Stores" },
  { code: '5697', description: 'Tailors, Seamstresses & Alterations' },
  { code: '5698', description: 'Wig & Toupee Shops' },
  { code: '5699', description: 'Miscellaneous Apparel & Accessory Shops' },
  { code: '5712', description: 'Furniture, Home Furnishings Stores' },
  { code: '5713', description: 'Floor Covering Stores' },
  { code: '5714', description: 'Drapery & Upholstery Stores' },
  { code: '5718', description: 'Fireplace & Fireplace Screen Stores' },
  { code: '5719', description: 'Miscellaneous Home Furnishing Stores' },
  { code: '5722', description: 'Household Appliance Stores' },
  { code: '5732', description: 'Electronics Stores' },
  { code: '5733', description: 'Music Stores – Instruments & Sheet Music' },
  { code: '5734', description: 'Computer Software Stores' },
  { code: '5735', description: 'Record, Music & CD Stores' },
  { code: '5811', description: 'Caterers' },
  { code: '5812', description: 'Eating Places, Restaurants' },
  { code: '5813', description: 'Bars, Cocktail Lounges & Nightclubs' },
  { code: '5814', description: 'Fast Food Restaurants' },
  { code: '5815', description: 'Digital Goods – Media, Books, Movies, Music' },
  { code: '5816', description: 'Digital Goods – Games' },
  { code: '5817', description: 'Digital Goods – Applications' },
  { code: '5818', description: 'Digital Goods – Large Digital Goods' },
  { code: '5912', description: 'Drug Stores & Pharmacies' },
  { code: '5921', description: 'Package Stores – Beer, Wine & Liquor' },
  { code: '5931', description: 'Second Hand Stores' },
  { code: '5932', description: 'Antique Shops' },
  { code: '5933', description: 'Pawn Shops' },
  { code: '5935', description: 'Wrecking & Salvage Yards' },
  { code: '5937', description: 'Antique Reproduction Stores' },
  { code: '5940', description: 'Bicycle Shops' },
  { code: '5941', description: 'Sporting Goods Stores' },
  { code: '5942', description: 'Book Stores' },
  { code: '5943', description: 'Stationery & Office Supply Stores' },
  { code: '5944', description: 'Jewelry, Watch & Silverware Stores' },
  { code: '5945', description: 'Hobby, Toy & Game Shops' },
  { code: '5946', description: 'Camera & Photographic Supply Stores' },
  { code: '5947', description: 'Gift, Card, Novelty & Souvenir Shops' },
  { code: '5948', description: 'Luggage & Leather Goods Stores' },
  { code: '5949', description: 'Sewing, Needlework & Fabric Stores' },
  { code: '5950', description: 'Glassware & Crystal Stores' },
  { code: '5964', description: 'Direct Marketing – Catalog Merchants' },
  { code: '5965', description: 'Direct Marketing – Combination Catalog & Retail' },
  { code: '5966', description: 'Direct Marketing – Outbound Telemarketing' },
  { code: '5967', description: 'Direct Marketing – Inbound Telemarketing' },
  { code: '5968', description: 'Direct Marketing – Subscription Merchants' },
  { code: '5969', description: 'Direct Marketing – Other' },
  { code: '5970', description: 'Artist Supply & Craft Shops' },
  { code: '5971', description: 'Art Dealers & Galleries' },
  { code: '5972', description: 'Stamp & Coin Stores' },
  { code: '5973', description: 'Religious Goods Stores' },
  { code: '5975', description: 'Hearing Aid Sales & Supplies' },
  { code: '5976', description: 'Orthopedic Goods & Prosthetic Devices' },
  { code: '5977', description: 'Cosmetic Stores' },
  { code: '5978', description: 'Typewriter Stores' },
  { code: '5992', description: 'Florists' },
  { code: '5993', description: 'Cigar Stores & Stands' },
  { code: '5994', description: 'News Dealers & Newsstands' },
  { code: '5995', description: 'Pet Shops, Pet Food & Supplies' },
  { code: '5996', description: 'Swimming Pool Services & Supplies' },
  { code: '5997', description: 'Electric Razor Stores' },
  { code: '5998', description: 'Tent & Awning Shops' },
  { code: '5999', description: 'Miscellaneous & Specialty Retail Stores' },
  { code: '6010', description: 'Financial Institutions – Manual Cash Disbursements' },
  { code: '6011', description: 'Financial Institutions – ATM Cash Disbursements' },
  { code: '6012', description: 'Financial Institutions – Merchandise & Services' },
  { code: '6051', description: 'Non-Financial Institutions – Foreign Currency, Money Orders' },
  { code: '6300', description: 'Insurance Sales & Services' },
  { code: '6513', description: 'Real Estate Agents & Managers' },
  { code: '7011', description: 'Hotels, Motels & Resorts' },
  { code: '7012', description: 'Timeshares' },
  { code: '7032', description: 'Sporting & Recreational Camps' },
  { code: '7033', description: 'Trailer Parks & Campgrounds' },
  { code: '7210', description: 'Laundry, Cleaning & Garment Services' },
  { code: '7211', description: 'Laundries – Family & Commercial' },
  { code: '7216', description: 'Dry Cleaners' },
  { code: '7217', description: 'Carpet & Upholstery Cleaning' },
  { code: '7221', description: 'Photographic Studios' },
  { code: '7230', description: 'Barber & Beauty Shops' },
  { code: '7251', description: 'Shoe Repair & Hat Cleaning Shops' },
  { code: '7261', description: 'Funeral Services & Crematories' },
  { code: '7273', description: 'Dating & Escort Services' },
  { code: '7278', description: 'Buying & Shopping Services / Clubs' },
  { code: '7296', description: 'Clothing Rental Services' },
  { code: '7297', description: 'Massage Parlors' },
  { code: '7298', description: 'Health & Beauty Spas' },
  { code: '7299', description: 'Miscellaneous Personal Services' },
  { code: '7311', description: 'Advertising Services' },
  { code: '7321', description: 'Consumer Credit Reporting Agencies' },
  { code: '7333', description: 'Commercial Photography, Art & Graphics' },
  { code: '7338', description: 'Quick Copy & Reproduction Services' },
  { code: '7339', description: 'Secretarial Support Services' },
  { code: '7342', description: 'Exterminating & Disinfecting Services' },
  { code: '7349', description: 'Cleaning & Maintenance – Building Services' },
  { code: '7361', description: 'Employment Agencies & Temp Help Services' },
  { code: '7372', description: 'Computer Programming & Data Processing' },
  { code: '7375', description: 'Information Retrieval Services' },
  { code: '7379', description: 'Computer Repair & Maintenance Services' },
  { code: '7392', description: 'Management, Consulting & PR Services' },
  { code: '7393', description: 'Detective Agencies & Security Services' },
  { code: '7394', description: 'Equipment Rental & Leasing Services' },
  { code: '7395', description: 'Photofinishing Laboratories' },
  { code: '7399', description: 'Business Services' },
  { code: '7512', description: 'Automobile Rental Agency' },
  { code: '7513', description: 'Truck & Utility Trailer Rentals' },
  { code: '7519', description: 'Motor Home & Recreational Vehicle Rentals' },
  { code: '7523', description: 'Parking Lots & Garages' },
  { code: '7531', description: 'Automotive Body Repair Shops' },
  { code: '7534', description: 'Tire Retreading & Repair Shops' },
  { code: '7535', description: 'Automotive Paint Shops' },
  { code: '7538', description: 'Automotive Service Shops' },
  { code: '7542', description: 'Car Washes' },
  { code: '7549', description: 'Towing Services' },
  { code: '7622', description: 'Electronics Repair Shops' },
  { code: '7623', description: 'Air Conditioning & Refrigeration Repair' },
  { code: '7629', description: 'Electrical & Small Appliance Repair Shops' },
  { code: '7631', description: 'Watch, Clock & Jewelry Repair' },
  { code: '7641', description: 'Furniture Repair & Upholstery' },
  { code: '7692', description: 'Welding Services' },
  { code: '7699', description: 'Miscellaneous Repair Shops' },
  { code: '7829', description: 'Motion Picture & Video Tape Production' },
  { code: '7832', description: 'Motion Picture Theaters' },
  { code: '7841', description: 'Video Tape Rental Stores' },
  { code: '7911', description: 'Dance Halls, Studios & Schools' },
  { code: '7922', description: 'Theatrical Producers & Ticket Agencies' },
  { code: '7929', description: 'Bands, Orchestras & Entertainers' },
  { code: '7932', description: 'Billiard & Pool Establishments' },
  { code: '7933', description: 'Bowling Alleys' },
  { code: '7941', description: 'Sports Clubs, Athletic Fields & Fitness Centers' },
  { code: '7991', description: 'Tourist Attractions & Exhibits' },
  { code: '7992', description: 'Golf Courses – Public' },
  { code: '7993', description: 'Video Amusement Game Supplies' },
  { code: '7994', description: 'Video Game Arcades' },
  { code: '7995', description: 'Betting, Casino Gambling & Lottery' },
  { code: '7996', description: 'Amusement Parks, Circuses & Carnivals' },
  { code: '7997', description: 'Membership Clubs – Country, Golf, Sports' },
  { code: '7998', description: 'Aquariums & Seaquariums' },
  { code: '7999', description: 'Recreation Services' },
  { code: '8011', description: 'Doctors & Physicians' },
  { code: '8021', description: 'Dentists & Orthodontists' },
  { code: '8031', description: 'Osteopaths' },
  { code: '8041', description: 'Chiropractors' },
  { code: '8042', description: 'Optometrists & Ophthalmologists' },
  { code: '8043', description: 'Opticians & Eyeglass Stores' },
  { code: '8049', description: 'Podiatrists & Chiropodists' },
  { code: '8050', description: 'Nursing & Personal Care Facilities' },
  { code: '8062', description: 'Hospitals' },
  { code: '8071', description: 'Medical & Dental Laboratories' },
  { code: '8099', description: 'Health Practitioners & Medical Services' },
  { code: '8111', description: 'Legal Services & Attorneys' },
  { code: '8211', description: 'Elementary & Secondary Schools' },
  { code: '8220', description: 'Colleges, Universities & Professional Schools' },
  { code: '8241', description: 'Correspondence & Online Schools' },
  { code: '8244', description: 'Business & Secretarial Schools' },
  { code: '8249', description: 'Vocational & Trade Schools' },
  { code: '8299', description: 'Educational Services' },
  { code: '8351', description: 'Child Care Services' },
  { code: '8398', description: 'Charitable & Social Service Organizations' },
  { code: '8641', description: 'Civic, Social & Fraternal Associations' },
  { code: '8651', description: 'Political Organizations' },
  { code: '8661', description: 'Religious Organizations' },
  { code: '8675', description: 'Automobile Associations' },
  { code: '8699', description: 'Membership Organizations' },
  { code: '8734', description: 'Testing Laboratories (Non-Medical)' },
  { code: '8911', description: 'Architectural, Engineering & Surveying Services' },
  { code: '8931', description: 'Accounting, Auditing & Bookkeeping Services' },
  { code: '8999', description: 'Professional Services' },
  { code: '9211', description: 'Court Costs & Alimony' },
  { code: '9222', description: 'Fines' },
  { code: '9311', description: 'Tax Payments' },
  { code: '9399', description: 'Government Services' },
  { code: '9402', description: 'Postal Services – Government Only' },
  { code: '9950', description: 'Intra-Company Purchases' },
];

/** Sorted for display; keep the search index built from this. */
export const SORTED_MCC_CODES: MccCode[] = [...MCC_CODES].sort((a, b) =>
  a.description.localeCompare(b.description),
);

export function findMccByCode(code: string): MccCode | undefined {
  return MCC_CODES.find((m) => m.code === code);
}

export function formatMccLabel(mcc: MccCode): string {
  return `${mcc.description} – ${mcc.code}`;
}
